spring.datasource.url=jdbc:postgresql://localhost:5432/aldia_db
spring.datasource.username=${DB_USUARIO}
spring.datasource.password=${DB_CONTRASENA}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

jwt.clave-secreta=${JWT_CLAVE_SECRETA}
jwt.expiracion-ms=86400000
cors.origenes-permitidos=http://localhost:4200